#!/bin/sh

set -e

echo building...
npm run build

echo deploying to gh-pages branch...
cd dist
git init
git add -A
git co -b gh-pages
git commit -m 'deploy to github pages'
git push https://github.com/mposk98/wasm-game-of-life.git gh-pages
git co master
cd ..
