#!/bin/sh

set -e

rm -rf dist

echo building...
npm run build

echo deploying to gh-pages branch...
cd dist
git init
git add -A
git checkout -b gh-pages
git commit -m 'deploy to github pages'
git push --force https://github.com/mposk98/wasm-game-of-life.git gh-pages
cd ..
