#!/bin/sh

set -e

echo building...
npm run build

echo deploying to gh-pages branch...
cd dist
git init
git add -A
git checkout --orphan tmp_branch
git commit -m 'deploy to github pages'
git branch -D gh-pages
git branch -m gh-pages
git push --force https://github.com/mposk98/wasm-game-of-life.git gh-pages
cd ..
